### ISSUE TITLE
Hi , i am very interested in your work.

### ISSUE THREAD

**Issue by shz1314** [xinntao/SFTGAN#1]
Hi,
  Thanks to your very outstanding work, but i just can code in pytorch. Can you give me the pytorch code just for model or SFT layer. 
                                                                                                                                              Thanks.
                                                                                                                                               Gundati

**Comment by xinntao** [comment]
Pytorch code is under development. It will be released within two weeks.

**Comment by xinntao** [comment]
@shz1314 Pytorch code is under development. It will be finished and released within 2 weeks. Thanks.

**Comment by xinntao** [comment]
@shz1314, I have just added raw sft-gan testing codes to pytorch repo. Please see the _sft-arch.py_ file in [BasicSR repo](https://github.com/xinntao/BasicSR/tree/master/codes/models/modules).

The sft-gan models can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1o2J8SwWaDZ69w3tyTevtakU6QrMHcYPk?usp=sharing).

You can first run [test_seg.py](https://github.com/xinntao/BasicSR/blob/master/codes/test_seg.py), and then test sft in sft_arch.py. We will improve the codes in the next days.
