### ISSUE TITLE
hi about SFT layer

### ISSUE THREAD

**Issue by shz1314** [xinntao/SFTGAN#3]
I am sorry to trouble you, i want to introduce your SFT layer in my image-to-image translation work.If you have already finished SFT layer in pytorch, please send it to me. Very very thanks. My email is haoze_song_jnu@163.com
thanks
haoze

**Comment by xinntao** [comment]
@shz1314, I have just added raw sft-gan testing codes to pytorch repo. Please see the _sft-arch.py_ file in [BasicSR repo](https://github.com/xinntao/BasicSR/tree/master/codes/models/modules).

Note that pre-training is import to sft-gan. In our implementation, we first train a normal SR network (with BN layers) under GAN architecture and then we substitute the BN layers with SFT layers (use the BN parameters as the initialization) [_BN layers can also be kept and insert new SFT layers_].

We will add the training codes in pytorch later. Also, we will explore more stable and effective training.
